apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: techify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:     
      automountServiceAccountToken: false 
      containers:
      - name: backend
        image: saikishore1903/techify-backend:v1.0
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: techify-env
            optional: false
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "512Mi"
            cpu: "500m"
            ephemeral-storage: "2Gi"

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: techify
spec:
  selector:
    app: backend
  ports: 
  - port: 5000
    targetPort: 5000
    protocol: TCP
 
