apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: techify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: saikishore1903/techify-backend:v1.0
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: techify-env
---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: techify
spec:
  selector:
    app: backend
  ports: 
  - port: 5000
    targetPort: 5000
    protocol: TCP
 
