apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: techify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: saikishore1903/techify-frontend:v1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: techify
spec:
  selector:
    app: frontend
  type: NodePort
  ports: 
  - port: 80
    targetPort: 80
    protocol: TCP
 
